AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-engine

  Sample SAM Template for sam-engine


Globals:
  Function:
    Timeout: 3

Resources:
  CreatePolicyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.create_policy.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Auth:
        DefaultAuthorizer: Authorizer
        Authorizers:
          AuthorizerFunction:
            FunctionPayloadType: REQUEST
            FunctionArn: 
              GetAtt: AuthorizerFunction.Arn
            Identity:
              Headers:
                - Authorization
      Events:
        CreatePolicy:
          Type: Api 
          Properties:
            Path: /create-policy
            Method: post

  CreateTenantFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.create_tenant.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateTenant:
          Type: Api 
          Properties:
            Path: /create-tenant
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.login.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateTenant:
          Type: Api 
          Properties:
            Path: /login
            Method: post

  EngineFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.engine.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateEngine:
          Type: Api 
          Properties:
            Path: /create-engine
            Method: post
      Auth:
        DefaultAuthorizer: Authorizer
        Authorizers:
          AuthorizerAPIKeyFunction:
            FunctionPayloadType: REQUEST
            FunctionArn: 
              GetAtt: AuthorizerAPIKeyFunction.Arn
            Identity:
              Headers:
                - x-api-key

  AuthorizerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.authorizer.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

  AuthorizerAPIKeyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.authorizer_api_key.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

