AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-engine

  Sample SAM Template for sam-engine

Parameters:
  DbConnection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /db/DbConnection

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        DEBUG: "0"
        DB_CONNECT: !Ref DbConnection
    VpcConfig:
      SecurityGroupIds:
        - sg-086a0d64f78b151e5
      SubnetIds:
        - subnet-0b52b7916b3b646c7

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AuthorizerTokenFunction
        Authorizers:
          AuthorizerTokenFunction:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
          AuthorizerAPIKeyFunction:
            FunctionArn: !GetAtt AuthorizerAPIKeyFunction.Arn

  CreatePolicyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: create_policy.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreatePolicy:
          Type: Api 
          Properties:
            Path: /create-policy
            Method: post
            RestApiId: !Ref ApiGateway

  CreateTenantFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: create_tenant.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateTenant:
          Type: Api 
          Properties:
            Path: /create-tenant
            Method: post
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: None
              
  LoginFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: login.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateTenant:
          Type: Api 
          Properties:
            Path: /login
            Method: post
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: None

  EngineFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: engine.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateEngine:
          Type: Api 
          Properties:
            Path: /create-engine
            Method: post 
            RestApiId: !Ref ApiGateway
            Auth:
              Authorizer: AuthorizerAPIKeyFunction

  AuthorizerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: authorizer.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

  AuthorizerAPIKeyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: authorizer_api_key.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

  MigrateFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: migrate.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

