AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-engine

  Sample SAM Template for sam-engine

Parameters:
  DbConnection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /db/DbConnection

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        DEBUG: False
        DB_CONNECT: !Ref DbConnection

Resources:

  CreatePolicyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: create_policy.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreatePolicy:
          Type: Api 
          Properties:
            Path: /create-policy
            Method: post
            Auth:
              DefaultAuthorizer: AuthorizerFunction
              Authorizers:
                AuthorizerFunction:
                  FunctionPayloadType: REQUEST
                  FunctionArn: 
                    GetAtt: AuthorizerFunction.Arn
                  Identity:
                    Headers:
                      - Authorization

  CreateTenantFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: create_tenant.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateTenant:
          Type: Api 
          Properties:
            Path: /create-tenant
            Method: post

  LoginFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: login.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateTenant:
          Type: Api 
          Properties:
            Path: /login
            Method: post

  EngineFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: engine.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CreateEngine:
          Type: Api 
          Properties:
            Path: /create-engine
            Method: post
            Auth:
              DefaultAuthorizer: AuthorizerAPIKeyFunction
              Authorizers:
                AuthorizerAPIKeyFunction:
                  FunctionPayloadType: REQUEST
                  FunctionArn: 
                    GetAtt: AuthorizerAPIKeyFunction.Arn
                  Identity:
                    Headers:
                      - x-api-key

  AuthorizerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: authorizer.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

  AuthorizerAPIKeyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: authorizer_api_key.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

