AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-engine

  Sample SAM Template for sam-engine


Globals:
  Function:
    Timeout: 3

Resources:
  CreatePolicyFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.create_policy.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Auth:
        DefaultAuthorizer: MyAuthorizer
        Authorizers:
          AuthorizerFunction:
            FunctionPayloadType: REQUEST
            FunctionArn: 
              GetAtt: AuthorizerFunction.Arn
            Identity:
              Headers:
                - Authorization
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

  AuthorizerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: handlers.authorizer.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
