"""add_password_column

Revision ID: 0f8c98713464
Revises: ed6bfdafe362
Create Date: 2023-10-01 16:29:42.081127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f8c98713464"
down_revision: Union[str, None] = "ed6bfdafe362"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("partners", sa.Column("password", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partners", "password")
    # ### end Alembic commands ###
