"""add_api_key

Revision ID: 7bceb53940e0
Revises: 0f8c98713464
Create Date: 2023-10-01 17:18:55.325088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7bceb53940e0"
down_revision: Union[str, None] = "0f8c98713464"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("partners", sa.Column("api_key", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("partners", "api_key")
    # ### end Alembic commands ###
